/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * User_Home.java
 *
 * Created on Nov 19, 2014, 10:10:53 PM
 */

package cour;

/**
 *
 * @author sowmya
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class User_Home extends javax.swing.JFrame {

    /** Creates new form User_Home */
    public User_Home() {
        initComponents();
    }
     

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

      
 jPanel1 = new javax.swing.JPanel();
       
 jLabel1 = new javax.swing.JLabel();
       
 jLabel2 = new javax.swing.JLabel();
       
 jLabel3 = new javax.swing.JLabel();
       
 jTextField1 = new javax.swing.JTextField();
       
 jButton1 = new javax.swing.JButton();
       
 jButton2 = new javax.swing.JButton();
       
 jPasswordField1 = new javax.swing.JPasswordField();
       
 jLabel5 = new javax.swing.JLabel();
       
 jButton4 = new javax.swing.JButton();
       
 jLabel6 = new javax.swing.JLabel();
       
 jLabel7 = new javax.swing.JLabel();
       
 jLabel8 = new javax.swing.JLabel();
       
 jTextField2 = new javax.swing.JTextField();
       
 jPasswordField2 = new javax.swing.JPasswordField();
       
 jButton3 = new javax.swing.JButton();
       
 jButton5 = new javax.swing.JButton();

        
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
setBackground(new java.awt.Color(-16776961,true));
        
setForeground(new java.awt.Color(-4144960,true));

       
 jLabel1.setText("Existing Users Login :");

       
 jLabel2.setText("ID");

       
 jLabel3.setText("Password");

       
 jButton1.setText("SignIN");
       
 jButton1.addActionListener(new java.awt.event.ActionListener() {
           
 public void actionPerformed(java.awt.event.ActionEvent evt) {
               
 jButton1ActionPerformed(evt);
           
 }
        
});

       
 jButton2.setText("Reset");
       
 jButton2.addActionListener(new java.awt.event.ActionListener() {
            
public void actionPerformed(java.awt.event.ActionEvent evt) {
               
 jButton2ActionPerformed(evt);
            }
        });

       
 javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       
 jPanel1.setLayout(jPanel1Layout);
       
 jPanel1Layout.setHorizontalGroup(
  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel5.setText("New User Sign Up ");

        jButton4.setText("Go To Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Name :");

        jLabel8.setText("Password :");

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jButton3)
                                .addGap(27, 27, 27)
                                .addComponent(jButton5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton5)))
                    .addComponent(jLabel8))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jPasswordField1.setText(null);
        jLabel6.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Welocome().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(null);
        jPasswordField2.setText(null);
        jLabel6.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
                Connection conn = null;
		String driverName = "oracle.jdbc.OracleDriver";
		String url = "jdbc:oracle:thin:@127.0.0.1:1521:XE";
		Class.forName(driverName);
		conn = DriverManager.getConnection(url, "system", "sowmi");
                String temp=new String(jPasswordField2.getPassword());
		CallableStatement vStatement = conn.prepareCall( "{ ? = call insert_signup( ?,? ) }" );
		vStatement.setString( 2, jTextField2.getText());
		vStatement.setString( 3, temp );
		vStatement.registerOutParameter( 1, Types.VARCHAR );
		vStatement.executeUpdate();
		int result = vStatement.getInt( 1 );
                if(result == 1)
                    jLabel6.setText("Sign up unsuccessful");
                else
                {
                    jLabel6.setText("Successfully Signed up. Your id is " + result);
                conn.close();
              jTextField2.setText(null);
                jPasswordField2.setText(null);
        
            }
                    
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          int n=0;
         try{
             Integer.parseInt(jTextField1.getText());
                    }catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Invalid ID. Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
                    n=1;
                    }
          if(n==0)
          try{
                Connection conn = null;
		String driverName = "oracle.jdbc.OracleDriver";
		String url = "jdbc:oracle:thin:@127.0.0.1:1521:XE";
		Class.forName(driverName);
		conn = DriverManager.getConnection(url, "system", "sowmi");
                CallableStatement vStatement = conn.prepareCall( "{ ? = call login_check( ?,? ) }" );
                
		vStatement.setString( 2, jTextField1.getText());
                String temp=new String(jPasswordField1.getPasword());
		
vStatement.setString( 3, temp );
		
vStatement.registerOutParameter( 1, Types.VARCHAR );
		
vStatement.executeUpdate();
		
String result = vStatement.getString( 1 );
                
if(result.equals("0"))
                {
                   
 jLabel6.setText("Invalid ID or Password");
             
   }

                
else if(result.equals("1"))
                {

                   conn.close();
                  
 	 setVisible(false);
                   
	new Application(jTextField1.getText()).setVisible(true);
                    
}
                else if(result.equals("na"))
                {
                   
	conn.close();
                  
	 setVisible(false);
                   
	String msg = "Sorry, Your application has not been validated yet. Thanks";
                  
	 new ResponceForm(jTextField1.getText(),msg).setVisible(true);
                    
}
                
else if(result.equals("Rejected"))
                {
                 
  conn.close();
                  
 setVisible(false);
                   
String msg = "Your application has Cancelled.";
                   
new ResponceForm(jTextField1.getText(),msg).setVisible(true);
                  
  }
                
else if(result.equals("Selected"))
                {
                   
	conn.close();
                   
	setVisible(false);
                
	String msg = "1";
                   
	new ResponceForm(jTextField1.getText(),msg).setVisible(true);
                
 }

                   
 }
                
catch(Exception ex) {
           
 JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
      
  }
       

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    
public static void main(String args[]) {
       
	 java.awt.EventQueue.invokeLater(new Runnable() {
            
		public void run() {
                
			new User_Home().setVisible(true);
           
	 }
       
	 });
   
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
